ALMCourseGit.Web/Models/ErrorViewModel.cs
using System;

namespace ALMCourseGit.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ALMCourseGit.Web/ViewModels/DepositModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ALMCourseGit.Web.ViewModels
{
    public class DepositModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public decimal Amount { get; set; }
    }
}

ALMCourseGit.Web/ViewModels/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ALMCourseGit.Web.ViewModels
{
    public class TransactionViewModel
    {
        [Required]
        public DepositModel DepositModel { get; set; }
        [Required]
        public WithdrawModel WithdrawModel { get; set; }
    }
}

ALMCourseGit.Web/ViewModels/TransferViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ALMCourseGit.Web.ViewModels
{
    public class TransferViewModel
    {
        [Required]
        public int SenderAccountId { get; set; }
        [Required]
        public int ReceiverAccountId { get; set; }
        [Required]
        public decimal Amount { get; set; }
    }
}

ALMCourseGit.Web/ViewModels/WithdrawModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ALMCourseGit.Web.ViewModels
{
    public class WithdrawModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public decimal Amount { get; set; }
    }
}

ALMCourseGit.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ALMCourseGit.Web.Models;
using ALMCourseGit.Web.Database;

namespace ALMCourseGit.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = BankRepository.GetCustomers();
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ALMCourseGit.Web/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALMCourseGit.Web.Database;
using ALMCourseGit.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ALMCourseGit.Web.Controllers
{
    public class TransactionController : Controller
    {
        public IActionResult Index()
        {
            return View(new TransactionViewModel());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Withdraw(WithdrawModel model)
        {
            if (ModelState.IsValid)
            {
                TempData["Status"] = BankRepository.Withdraw(model.Id.ToString(), model.Amount.ToString());
                return View("Index");
            }
            TempData["Status"] = "Please fill out every field with valid numbers.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Deposit(DepositModel model)
        {
            if (ModelState.IsValid)
            {
                TempData["Status"] = BankRepository.Deposit(model.Id.ToString(), model.Amount.ToString());
                return View("Index");
            }
            TempData["Status"] = "Please fill out every field with valid numbers.";
            return RedirectToAction("Index");
        }
    }
}

ALMCourseGit.Web/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALMCourseGit.Web.Database;
using ALMCourseGit.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ALMCourseGit.Web.Controllers
{
    public class TransferController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(TransferViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            TempData["Status"] = BankRepository.Transfer(model.SenderAccountId, model.ReceiverAccountId, model.Amount);

            return View();
        }
    }
}

ALMCourseGit.Web/Views/Home/Index.cshtml
@model List<ALMCourseGit.Web.Database.Entities.Customer>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Gabriels Bank</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <ul class="text-center" style="list-style: none;">
        @foreach(var customer in Model)
        {
            <li class="card">
                <h3>Customer ID: @customer.CustomerId</h3>
                <p>Customer name: @customer.Name</p>
                <ul class="text-center" style="list-style: none;">
                    @foreach(var account in customer.Accounts)
                    {
                        <li>
                            <h5>Account ID: @account.AccountId</h5>
                            <p>Balance: @account.Balance</p>
                        </li>
                    }
                </ul>
            </li>
        }
    </ul>
</div>

ALMCourseGit.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@inject IHostingEnvironment environment

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ALMCourseGit.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gabriels Bank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Index">Transfer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ALMCourseGit.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <p>@environment.ApplicationName - @environment.EnvironmentName</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ALMCourseGit.Web/Views/Transaction/Index.cshtml
@model ALMCourseGit.Web.ViewModels.TransactionViewModel

<div class="container-fluid">
    <div class="text-center">
        <p>@TempData["Status"]</p>
    </div>
    <div class="row">
        <form class="col" asp-controller="Transaction" asp-action="Withdraw" method="post">
            <div class="row">
                <div class="input-group">
                    <label>
                        Account ID
                        <input asp-for="WithdrawModel.Id" name="id" />
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="input-group">
                    <label>
                        Amount
                        <input asp-for="WithdrawModel.Amount" name="amount" />
                    </label>
                </div>
            </div>
            
            <button type="submit">Withdraw</button>
        </form>
        <form class="col" asp-controller="Transaction" asp-action="Deposit" method="post">
            <div class="row">
                <div class="input-group">
                    <label>
                        Account ID
                        <input asp-for="DepositModel.Id" name="id" />
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="input-group">
                    <label>
                        Amount
                        <input asp-for="DepositModel.Amount" name="amount" />
                    </label>
                </div>
            </div>
            <button type="submit">Deposit</button>
        </form>
    </div>
</div>

ALMCourseGit.Web/Views/Transfer/Index.cshtml
@model ALMCourseGit.Web.ViewModels.TransferViewModel

<div class="container-fluid">
    <div class="text-center">
        <p>@TempData["Status"]</p>
    </div>
    <div class="row">
        <form class="col" asp-controller="Transfer" asp-action="Index" method="post">
            <div class="row">
                <div class="input-group">
                    <label>
                        From Account
                        <input asp-for="SenderAccountId"/>
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="input-group">
                    <label>
                        To Account
                        <input asp-for="ReceiverAccountId"/>
                    </label>
                </div>
            </div>
            
            <div class="row">
                <div class="input-group">
                    <label>
                        Amount
                        <input asp-for="Amount"/>
                    </label>
                </div>
            </div>

            <button type="submit">Transfer</button>
        </form>
    </div>
    
    <div asp-validation-summary="All">
    </div>
</div>